In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as pt

In [2]:
f1 = pd.read_csv("Restaurant_Reviews.tsv", delimiter= "\t", quoting = 3)

In [3]:
f1.head()

Review  Liked
0                           Wow... Loved this place.      1
1                                 Crust is not good.      0
2          Not tasty and the texture was just nasty.      0
3  Stopped by during the late May bank holiday of...      1
4  The selection on the menu was great and so wer...      1

In [4]:
import re
import nltk

In [5]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Parthraj\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [6]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [7]:
corpus = []
ps= PorterStemmer()
for i in range(0, len(f1)):
    review = re.sub("[^a-zA-Z]", " ", f1["Review"][i])
    print(review)
    review = review.lower()
    review = review.split()
    all_stopword= stopwords.words("english")
    all_stopword.remove('not')
    all_stopword.remove("aren't")
    all_stopword.remove("hasn't")
    all_stopword.remove("haven't")
    review1= []
    for j in review :
        if not j in all_stopword:
            review1.append(ps.stem(j))
            
    review= " ".join(review1)
    corpus.append(review)
            
   
    

Wow    Loved this place 
Crust is not good 
Not tasty and the texture was just nasty 
Stopped by during the late May bank holiday off Rick Steve recommendation and loved it 
The selection on the menu was great and so were the prices 
Now I am getting angry and I want my damn pho 
Honeslty it didn t taste THAT fresh  
The potatoes were like rubber and you could tell they had been made up ahead of time being kept under a warmer 
The fries were great too 
A great touch 
Service was very prompt 
Would not go back 
The cashier had no care what so ever on what I had to say it still ended up being wayyy overpriced 
I tried the Cape Cod ravoli  chicken  with cranberry   mmmm 
I was disgusted because I was pretty sure that was human hair 
I was shocked because no signs indicate cash only 
Highly recommended 
Waitress was a little slow in service 
This place is not worth your time  let alone Vegas 
did not like at all 
The Burrittos Blah 
The food  amazing 
Service is also cute 
I could care les

I live in the neighborhood so I am disappointed I won t be back here  because it is a convenient location 
I didn t know pulled pork could be soooo delicious 
You get incredibly fresh fish  prepared with care 
Before I go in to why I gave a   star rating please know that this was my third time eating at Bachi burger before writing a review 
I love the fact that everything on their menu is worth it 
Never again will I be dining at this place 
The food was excellent and service was very good 
Good beer   drink selection and good food selection 
Please stay away from the shrimp stir fried noodles 
The potato chip order was sad    I could probably count how many chips were in that box and it was probably around    
Food was really boring 
Good Service check 
This greedy corporation will NEVER see another dime from me 
Will never  ever go back 
As much as I d like to go back  I can t get passed the atrocious service and will never return 
In the summer  you can dine in a charming outdoor pa

It was a pale color instead of nice and char and has NO flavor 
The croutons also taste homemade which is an extra plus 
I got home to see the driest damn wings ever 
It ll be a regular stop on my trips to Phoenix 
I really enjoyed Crema Caf  before they expanded  I even told friends they had the BEST breakfast 
Not good for the money 
I miss it and wish they had one in Philadelphia 
We got sitting fairly fast  but  ended up waiting    minutes just to place our order  another    minutes before the food arrived 
They also have the best cheese crisp in town 
Good value  great food  great service 
Couldn t ask for a more satisfying meal 
The food is good 
It was awesome 
I just wanted to leave 
We made the drive all the way from North Scottsdale    and I was not one bit disappointed 
I will not be eating there again 
     THE OWNERS REALLY REALLY need to quit being soooooo cheap let them wrap my freaking sandwich in two papers not one 
I checked out this place a couple years ago and was n

My boyfriend tried the Mediterranean Chicken Salad and fell in love 
Their rotating beers on tap is also a highlight of this place 
Pricing is a bit of a concern at Mellow Mushroom 
Worst Thai ever 
If you stay in Vegas you must get breakfast here at least once 
I want to first say our server was great and we had perfect service 
The pizza selections are good 
I had strawberry tea  which was good 
Highly unprofessional and rude to a loyal patron 
Overall  a great experience 
Spend your money elsewhere 
Their regular toasted bread was equally satisfying with the occasional pats of butter    Mmmm    
The Buffet at Bellagio was far from what I anticipated 
And the drinks are WEAK  people 
 My order was not correct 
Also  I feel like the chips are bought  not made in house 
After the disappointing dinner we went elsewhere for dessert 
The chips and sals a here is amazing                   
We won t be returning 
This is my new fav Vegas buffet spot 
I seriously cannot believe that the owne

In [8]:
corpus

['wow love place',
 'crust not good',
 'not tasti textur nasti',
 'stop late may bank holiday rick steve recommend love',
 'select menu great price',
 'get angri want damn pho',
 'honeslti tast fresh',
 'potato like rubber could tell made ahead time kept warmer',
 'fri great',
 'great touch',
 'servic prompt',
 'would not go back',
 'cashier care ever say still end wayyy overpr',
 'tri cape cod ravoli chicken cranberri mmmm',
 'disgust pretti sure human hair',
 'shock sign indic cash',
 'highli recommend',
 'waitress littl slow servic',
 'place not worth time let alon vega',
 'not like',
 'burritto blah',
 'food amaz',
 'servic also cute',
 'could care less interior beauti',
 'perform',
 'right red velvet cake ohhh stuff good',
 'never brought salad ask',
 'hole wall great mexican street taco friendli staff',
 'took hour get food tabl restaur food luke warm sever run around like total overwhelm',
 'worst salmon sashimi',
 'also combo like burger fri beer decent deal',
 'like final blow

In [9]:
from sklearn.feature_extraction.text import CountVectorizer 
cv = CountVectorizer(max_features= 1500)
X = cv.fit_transform(corpus).toarray()
Y= f1.iloc[:,-1]

In [10]:
len(X[0])

1500

In [11]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [12]:
Y=Y

In [13]:
Y

0      1
1      0
2      0
3      1
4      1
      ..
995    0
996    0
997    0
998    0
999    0
Name: Liked, Length: 1000, dtype: int64

In [14]:
from sklearn.model_selection import train_test_split 

In [15]:
x_train, x_test, y_train, y_test = train_test_split(X,Y, test_size= 0.1, random_state= 0)

In [16]:
x_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [17]:
len(x_test)

100

In [18]:
from sklearn.naive_bayes import GaussianNB

In [19]:
gn= GaussianNB()

In [20]:
gn.fit(x_train,y_train)

GaussianNB()

In [21]:
y_pred= gn.predict(x_test)

In [22]:
y_pred

array([1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1], dtype=int64)

In [23]:
from sklearn.metrics import confusion_matrix , accuracy_score

In [24]:
confusion_matrix(y_test,y_pred)

array([[27, 24],
       [ 3, 46]], dtype=int64)

In [25]:
accuracy_score(y_test , y_pred)

0.73

In [26]:
string = str(input("Enter a review to Check it Good or Bad ! "))

Enter a review to Check it Good or Bad ! not good


In [27]:

import re
import nltk
nltk.download("stopwords")
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps  = PorterStemmer()
r = re.sub("[^a-zA-Z]"," ", string)
r = r.lower()
r= r.split()
All_stopwords= stopwords.words("english")
All_stopwords.remove("not")
for j in r:
    if not j in All_stopwords:
        r= [ps.stem(j)]
r = " ".join(r)
r =[r]

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Parthraj\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [28]:
x = cv.transform(r).toarray()

In [29]:
m= gn.predict(x)
if m==1:
    print("Yes, it's a nice review")
else:
    print("No, it's not a nice review")

Yes, it's a nice review
